name: 'Setup Job'
description: 'Setup Job'
inputs:
  ignore_dotnet_on_cake_cache_hit:
    description: 'Whether to ignore installing .NET SDK is cache cache is hit'
    default: 'false'
outputs:
  cake-cache-hit:
    description: 'If the cache for Cake was found or not'
    value: ${{ steps.cache-cake.outputs.cache-hit }}

runs:
  using: composite
  steps:

    # Caches
    - name: Cache Cake Frosting
      uses: actions/cache@v4
      id: cache-cake
      with:
        path: run
        key: run-${{ runner.os }}-${{ hashFiles('./build/**') }}
    - name: Cache Cake Tools
      uses: actions/cache@v4
      with:
        path: tools
        key: tools-${{ runner.os }}-${{ hashFiles('./build/**') }}
    - name: Cache .nuget
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          nuget-${{ runner.os }}-

    # Required SDKs
    - name: Install .NET SDK 6
      uses: actions/setup-dotnet@v4
      if: inputs.ignore_dotnet_on_cake_cache_hit == 'false' || steps.cache-cake.outputs.cache-hit != 'true'
      with:
        dotnet-version: 6.0.423
    - name: Install .NET SDK 7
      uses: actions/setup-dotnet@v4
      if: inputs.ignore_dotnet_on_cake_cache_hit == 'false' || steps.cache-cake.outputs.cache-hit != 'true'
      with:
        dotnet-version: 7.0.410
    - name: Install .NET SDK 8
      uses: actions/setup-dotnet@v4
      if: inputs.ignore_dotnet_on_cake_cache_hit == 'false' || steps.cache-cake.outputs.cache-hit != 'true'
      with:
        dotnet-version: 8.0.302
